//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Insync.rc
//
#define IDI_INSYNC_ICON                 1
#define IDI_ICON000                     2
#define IDI_ICON020                     3
#define IDI_ICON040                     4
#define IDI_ICON060                     5
#define IDI_ICON080                     6
#define IDI_ICON100                     7
#define IDI_ICON120                     8
#define IDI_ICON140                     9
#define IDI_ICON160                     10
#define IDI_ICON180                     11
#define IDI_ICON200                     12
#define IDI_ICON220                     13
#define IDI_ICON240                     14
#define IDI_ICON260                     15
#define IDI_ICON280                     16
#define IDI_ICON300                     17
#define IDI_ICON320                     18
#define IDI_ICON340                     19
#define IDI_SIG_ICON                    20
#define IDI_MIRROR                      21
#define IDI_CLONE                       22
#define IDI_ADD                         23
#define IDI_EDIT                        24
#define IDI_REMOVE                      25
#define IDI_RUN                         26
#define IDI_SIMULATE                    27
#define IDI_ABORT                       28
#define IDI_SCHEDULE                    29
#define IDI_SAVE                        30
#define IDI_HELP                        31
#define IDI_EXCLUDE                     32
#define IDI_VIEW                        33
#define IDI_LED_GREEN                   34
#define IDI_LED_YELLOW                  35
#define IDI_LED_RED                     36
#define IDD_EVENT_DIALOG                101
#define IDD_EXCLUDED_DIRECTORIES_DIALOG 102
#define IDD_INSYNC_DIALOG               103
#define IDD_JOB_EDIT_DIALOG             104
#define IDC_ABORT_JOBS_BUTTON           200
#define IDC_ADD_BUTTON                  201
#define IDC_ADD_JOB_BUTTON              203
#define IDC_ADD_SRC_BUTTON              204
#define IDC_ADD_TRG_BUTTON              205
#define IDC_AUTO_DELETE_CHECK           206
#define IDC_BYTES_BYPASSED_STATIC       208
#define IDC_BYTES_COPIED_STATIC         209
#define IDC_BYTES_DELETED_STATIC        210
#define IDC_BYTES_UPDATED_STATIC        211
#define IDC_CHANGE_SRC_BUTTON           212
#define IDC_CHANGE_TRG_BUTTON           213
#define IDC_CLONE_JOB_BUTTON            214
#define IDC_COMMENT_EDIT                215
#define IDC_COMMENT_STATIC              216
#define IDC_CONFIG_STATIC               217
#define IDC_COPYRIGHT_STATIC            219
#define IDC_CRITERIA_STATIC             220
#define IDC_DAYLY_RADIO                 221
#define IDC_TIPS_OFF_CHECK              221
#define IDC_DIR_COPIED_STATIC           222
#define IDC_DIR_DELETED_STATIC          223
#define IDC_EDIT_JOB_BUTTON             225
#define IDC_END_DATE_DATETIMEPICKER     227
#define IDC_ELAPSED_STATIC              227
#define IDC_END_DATE_STATIC             228
#define IDC_EVENT_JOB_LIST              229
#define IDC_EVENT_NAME_EDIT             231
#define IDC_EXCLUDED_DIRECTORY_LIST     232
#define IDC_FILE_BYPASSED_STATIC        233
#define IDC_FILE_COPIED_STATIC          234
#define IDC_FILE_DELETED_STATIC         235
#define IDC_FILE_ERRORS_STATIC          236
#define IDC_FILE_UPDATED_STATIC         237
#define IDC_HAS_END_DATE_CHECK          238
#define IDC_INSYNC_STATIC               240
#define IDC_JOB_ERROR_POPUP_CHECK       243
#define IDC_JOB_LIST                    244
#define IDC_JOB_LOG_APPEND_CHECK        245
#define IDC_JOB_LOG_EDIT                246
#define IDC_JOB_LOG_SUMMARY_CHECK       247
#define IDC_JOB_LOG_SKIP_CHECK          248
#define IDC_JOB_LOG_STATIC              249
#define IDC_JOB_LOG_SYNC_DIR_CHECK      250
#define IDC_JOB_MODE_COMBO              251
#define IDC_JOB_NAME_EDIT               252
#define IDC_JOB_PROMPT_BEFORE_RUNNING_CHECK 252
#define IDC_JOB_VERIFY_CHECK            253
#define IDC_VERBOSE_LOG_CHECK           254
#define IDC_LED_ICON_STATIC             255
#define IDC_LED_STATIC                  256
#define IDC_MANDALA_STATIC              258
#define IDC_MAX_THREADS_COMBO           259
#define IDC_MAX_THREADS_STATIC          260
#define IDC_MIRROR_JOB_BUTTON           261
#define IDC_MONTHLY_RADIO               262
#define IDC_ONCE_RADIO                  263
#define IDC_PARAMETERS_EDIT             264
#define IDC_REMOVE_BUTTON               268
#define IDC_REMOVE_JOB_BUTTON           270
#define IDC_REMOVE_SRC_BUTTON           271
#define IDC_REMOVE_TRG_BUTTON           272
#define IDC_RUN_JOBS_BUTTON             274
#define IDC_SIMULATE_JOBS_BUTTON        279
#define IDC_SRC_DIR_LIST                281
#define IDC_SRC_EXCL_EDIT               282
#define IDC_SRC_EXCL_STATIC             283
#define IDC_SRC_EXCLUDED_DIR_BUTTON     284
#define IDC_SRC_FILTER_GRP              285
#define IDC_SRC_INCL_EDIT               286
#define IDC_SRC_INCL_STATIC             287
#define IDC_SRC_VOL_CHECK               289
#define IDC_START_DATE_DATETIMEPICKER   290
#define IDC_START_TIME_DATETIMEPICKER   291
#define IDC_STARTUP_RADIO               292
#define IDC_STATIC_FOLDER_GROUP         293
#define IDC_STATIC_PROGRESS_GROUP       294
#define IDC_SUBDIRS_CHECK               295
#define IDC_TRG_DIR_LIST                298
#define IDC_TRG_EXCL_EDIT               299
#define IDC_TRG_EXCL_STATIC             300
#define IDC_TRG_FILTER_GRP              301
#define IDC_TRG_GROUP_STATIC            302
#define IDC_TRG_INCL_EDIT               303
#define IDC_TRG_INCL_STATIC             304
#define IDC_TRG_VOL_CHECK               307
#define IDC_USER_NAME_EDIT              309
#define IDC_USER_NAME_STATIC            310
#define IDC_USER_PASSWORD_EDIT          311
#define IDC_USER_PASSWORD_STATIC        312
#define IDC_VIEW_LOG_BUTTON             316
#define IDC_WEEKLY_RADIO                317
#define IDC_JOB_GROUP_CTRL              318
#define IDC_XFER_STATIC                 319
#define IDC_SRC_GROUP_STATIC            321
#define IDC_COPY_ACLS_COMBO             322
#define IDC_RUNNING_THREADS_PROGRESS    324
#define IDC_DONT_DELETE_CHECK           328
#define IDC_RUN_AFTER_LIST              334
#define IDC_END_OF_RUN_COMBO            336
#define IDC_END_OF_RUN_STATIC           337

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        504
#define _APS_NEXT_COMMAND_VALUE         600
#define _APS_NEXT_CONTROL_VALUE         338
#define _APS_NEXT_SYMED_VALUE           701
#endif
#endif
